executionmgmt/urls.py
from django.conf.urls import patterns, include, url
import executionmgmt.views as exec_views



urlpatterns = patterns('',
   
    url(r'^$', exec_views.index),
    url(r'^get/(?P<tp_id>\d+)/$', exec_views.get_execution_detail),
    url(r'^start/$', exec_views.start_execution),
    #url(r'^(?P<p_id>\d+)/category/add/$', exec_views.add_category),
    url(r'^execute/(?P<tp_id>\d+)/tc/(?P<eh_id>\d+)/$', exec_views.execute),
    
    url(r'^get/(?P<tp_id>\d+)/filter/$', exec_views.filtered_data),
    url(r'^get/(?P<tp_id>\d+)/allocate/$', exec_views.allocate_task),
    url(r'^get/(?P<tp_id>\d+)/task/(?P<et_id>\d+)/$', exec_views.get_task_detail),
    url(r'^get/(?P<tp_id>\d+)/task/(?P<et_id>\d+)/testcase/$', exec_views.task_testcases),
    url(r'^get/(?P<tp_id>\d+)/task/(?P<et_id>\d+)/execute.psp$', exec_views.execute_tc),
    url(r'^get/(?P<tp_id>\d+)/task/(?P<et_id>\d+)/comment.psp$', exec_views.add_comment),
    
    url(r'^executionhistory/$', exec_views.get_execution_history),
    url(r'^testplan_status/$', exec_views.get_testplan_status),
    
    url(r'^exporttohtml/$', exec_views.report_view),
    
)

tcms/urls.py
from django.conf.urls import patterns, include, url
from testcasemgmt import urls as testcase_urls

from django.contrib import admin
admin.autodiscover()
handler404 = 'tcms.views.pagenotfound'
handler403 = 'tcms.views.notauthorized'

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^testcase/', include(testcase_urls)),
    (r'^$', 'tcms.views.index'),
	(r'^home/', 'tcms.views.home'),
    (r'^login/$','tcms.views.login'),
    (r'^auth/$','tcms.views.auth_view'),
    (r'^logout/$','tcms.views.logout'),
    (r'^invalid/$','tcms.views.invalid_login'),

    url(r'^project/', include('projectmgmt.urls')),
    url(r'^execution/', include('executionmgmt.urls')),
)

executionmgmt/models.py
from __future__ import division
from django.db import models as django_models
from projectmgmt import models as project_models
from testcasemgmt import models as tc_models
from django.contrib.auth.models import User 
from datetime import datetime

# Execution Models

class TestPlan(django_models.Model):
    project = django_models.ForeignKey(project_models.Project)
    build = django_models.ForeignKey(project_models.Build)
    title = django_models.CharField(max_length=200)
    description =  django_models.TextField()
    start_date = django_models.DateTimeField("Date", auto_now_add=True)
    started_by = django_models.ForeignKey(User)
    
    def get_categories(self):
        category_data = []
        
        
        categories = self.executiontask_set.values('category').distinct()
        
        
        for c in categories:
            category = project_models.Category.objects.get(id=c['category'])
            total_tc = ExecutionHistory.objects.filter(testcase__category = category).count()
            passed_tc = ExecutionHistory.objects.filter(testcase__category = category).filter(result="PASS").count()
            failed_tc = ExecutionHistory.objects.filter(testcase__category = category).filter(result="FAIL").count()
            nap_tc = ExecutionHistory.objects.filter(testcase__category = category).filter(result="NAp").count()
            ne_tc = ExecutionHistory.objects.filter(testcase__category = category).filter(result="NE").count()
            
            failed_testcases = ExecutionHistory.objects.filter(testcase__category = category).filter(result="FAIL")
            category_data.append({"category_name": category.name,
                                 "total_tc": total_tc, 
                                 "passed_tc": passed_tc,
                                 "failed_tc": failed_tc,
                                 "nap_tc": nap_tc,
                                 "ne_tc": ne_tc,
                                 "failed_testcases":failed_testcases})
            
        
        
        return category_data
    
        
    
    
    
class ExecutionTask(django_models.Model):
    testplan = django_models.ForeignKey(TestPlan)
    category = django_models.ForeignKey(project_models.Category)
    description =  django_models.TextField()
    title = django_models.CharField(max_length=200)
    allocated_by = django_models.ForeignKey(User, related_name = 'executiontask_allocated_by')
    allocated_to = django_models.ForeignKey(User,related_name = 'executiontask_allocated_to')
    start_date = django_models.DateTimeField("Date", auto_now_add=True)
    status = django_models.IntegerField(default=0)
    client_device = django_models.ForeignKey(project_models.ClientDevice)
    browsers = django_models.CharField(max_length=200, null=True, blank=True)    
    
    def __unicode__(self):
        return self.title
    
    def total(self):
        return self.executionhistory_set.count()
    
    def passed(self):
        return self.executionhistory_set.filter(result = 'PASS').count()
    
    def failed(self):
        return self.executionhistory_set.filter(result = 'FAIL').count()
    
    def nap(self):
        return self.executionhistory_set.filter(result = 'NAp').count()
 
    def not_ex(self):
        return self.executionhistory_set.filter(result = 'NE').count()

'''
class Execution(django_models.Model):
    project = django_models.ForeignKey(project_models.Project)
    
    title = django_models.CharField(max_length=200)
    started_by = django_models.ForeignKey(User)
    version = django_models.CharField(max_length=200)
    description =  django_models.TextField()
    start_date = django_models.DateField("Date", auto_now_add=True)
    status = django_models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.title
    
    def passed(self):
        return self.executionhistory_set.filter(result = 'PASS').count()
    
    def failed(self):
        return self.executionhistory_set.filter(result = 'FAIL').count()
    
    def nap(self):
        return self.executionhistory_set.filter(result = 'NAp').count()
'''
    
    
class ExecutionHistory(django_models.Model):
    execution = django_models.ForeignKey(ExecutionTask)
    testcase = django_models.ForeignKey(tc_models.TestCase)
    result = django_models.CharField(max_length=10,default='NE')
    bugid = django_models.IntegerField(default=0)
    comment = django_models.TextField(default='')
    executed_by = django_models.ForeignKey(User ,null=True, default = None)
    modified_date = django_models.DateField("Date", auto_now_add=True)
    
    def next(self):
        try:
            return ExecutionHistory.objects.get(pk=self.pk+1)
        except:
            return None

    def previous(self):
        try:
            return ExecutionHistory.objects.get(pk=self.pk-1)
        except:
            return None

    
    
    
    

projectmgmt/models.py
from django.db import models


# Project Models.

class Project(models.Model):
    name = models.CharField(max_length=200)
    description =  models.TextField()
    is_active = models.BooleanField(default = True)
    
    def __unicode__(self):
        return self.name
    

class Category(models.Model):
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=200)
    description =  models.TextField()
    is_active = models.BooleanField()
    
    def __unicode__(self):
        return self.name
    
class Build(models.Model):
    project = models.ForeignKey(Project)
    version = models.CharField(max_length=200)
    description =  models.TextField()
    
    def __unicode__(self):
        return self.version
    
    
       
    
class ClientDevice(models.Model):
    project = models.ForeignKey(Project)
    client_device = models.CharField(max_length=200)
    operating_system = models.CharField(max_length=200)
    
    def __unicode__(self):
        return self.client_device
    
class Browser(models.Model):
    browser = models.CharField(max_length=200)
    

executionmgmt/views.py
from __future__ import division
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from models import TestPlan, ExecutionHistory, ExecutionTask
from projectmgmt.models import Project, Category, Build, Browser, ClientDevice
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from testcasemgmt.models import TestCase, TestcaseHistory
from django.template import RequestContext
import time
from testcasemgmt.models import TestCase

from django.http.response import HttpResponse
from django.core.context_processors import csrf
from django.views.decorators.csrf import csrf_exempt



import datetime

import json
import commands


# Create your views here.
def index(request):
    testplans = TestPlan.objects.all()
    dict_obj = []
    for testplan in testplans:
        #print get_testplan_status(testplan.id)
        dict_obj.append({'testplan':testplan, 'status':get_testplan_status(testplan.id)})
    
    
    return render_to_response('executions_home.html', {'testplans' : testplans, 'dict_obj': dict_obj,'active':'active'}, context_instance=RequestContext(request))
    
def start_execution(request):
    args = {}
    args.update(csrf(request))
    
    projects = Project.objects.all()
    args['projects'] = projects
    args['active'] = 'active'
    
    if request.POST:
        
        title = request.POST['title']
        build = Build.objects.get(id=request.POST['build'])
        project = Project.objects.get(id=request.POST['project'])
        description = request.POST['description']
        
        test_plan = TestPlan(project = project, title = title, build = build , description = description, started_by = request.user)
        test_plan.save()
            
        return HttpResponseRedirect("/execution/")
        
    else:
        return render_to_response('start_execution.html', args)


def get_execution_detail(request, tp_id):
    testplan = TestPlan.objects.get(id = tp_id)
    execution_tasks = testplan.executiontask_set.all()
    #categories =  execution.executionhistory_set.values('testcase__category__name').distinct()
    
    return render_to_response('testplan_task_list.html', {'testplan': testplan,'execution_tasks': execution_tasks, 'active':'active'}, context_instance=RequestContext(request))

def execute(request, et_id):
    args = {}
    args.update(csrf(request))
    execution_task = ExecutionTask.objects.get(id = et_id)
    
    args['execution_task'] = execution_task
    
   
    '''
    if request.POST:
        
        result = request.POST['result']
        bug_id = request.POST['bugid']
        comment = request.POST['comment']
        
        if result == 'PASS':
            execution_history.bugid = 0
            execution_history.comment = ''
            if comment !='':
                execution_history.comment = comment
       
        else:
            if bug_id != '' and comment !='':
                execution_history.bugid = bug_id
                execution_history.comment = comment
        
        execution_history.result = result
        #print request.user
        execution_history.executed_by = request.user
        execution_history.save()
        
        # Calculate execution status.
        total_tc = execution_task.executionhistory_set.count()
        passed_tc = execution_task.executionhistory_set.filter(result='PASS').count()
        failed_tc = execution_task.executionhistory_set.filter(result='FAIL').count()
        nap_tc = execution_task.executionhistory_set.filter(result='NAp').count()
        
        
        
        execution_status = ( (passed_tc + failed_tc + nap_tc)/total_tc ) * 100
        
        #print execution_status 
        
        execution_task.status = execution_status
        
        execution_task.save()
          
        return render_to_response('execution.html', args)

        
    else:
        return render_to_response('execution.html', args)
    '''
    return render_to_response('execution.html', args, context_instance=RequestContext(request))
    


def filtered_data(request, ex_id):
    execution = TestPlan.objects.get(id = ex_id)
    execution_history = None
    filter_by = None
    
    categories =  execution.executionhistory_set.values_list('testcase__category__name', flat=True).distinct()
    
    
    
    if 'by' not in request.GET:
        by = "All"
        execution_history = execution.executionhistory_set.all()
    
    
        
        
    else:
        filter_by = request.GET['by']
    
        if filter_by == 'pass':
            by = "Passed"
            execution_history = execution.executionhistory_set.filter(result='PASS')
        elif filter_by == 'fail':
            by = "Failed"
            execution_history = execution.executionhistory_set.filter(result='FAIL')
        elif filter_by == 'nap':
            by = "Not Applicable"
            execution_history = execution.executionhistory_set.filter(result='NAp')
        elif filter_by == 'ne':
            by = "Not Executed"
            execution_history = execution.executionhistory_set.filter(result='NE')
        elif filter_by == 'executed':
            by = "Executed"
            execution_history = execution.executionhistory_set.filter(result__in=['PASS','FAIL','NAp'])
        else:
            by = "All"
            execution_history = execution.executionhistory_set.all()
    args = {}      
    args['execution'] = execution
    args['execution_history'] = execution_history 
    args['categories'] = categories
    #args['categories'] = execution.executionhistory_set.all().testcase_set.all()
    
    
    
    args['filter_by'] = by
    return render_to_response('execution_filter.html', args, context_instance=RequestContext(request))

def allocate_task(request, tp_id):
    args = {}
    args.update(csrf(request))
    testplan = TestPlan.objects.get(id = tp_id)
    args['testplan'] = testplan
    args['users'] = User.objects.all()
    args['browsers'] = Browser.objects.all()
    args['client_devices'] = ClientDevice.objects.all()
    
    
    if request.POST:
        
        title = request.POST['title']
        description = request.POST['description']
        allocate_to = User.objects.get(id=request.POST['allocate_to'])
        client_device = ClientDevice.objects.get(id=request.POST['client_device'])
        browsers = request.POST.getlist('browsers')
        browser_name = ''
        for browser in browsers:
            browser_name = browser_name + ',' + browser
                              
        browser_name =  browser_name[1:]
        category = Category.objects.get(id=request.POST['category'])
        
        execution_task = ExecutionTask(testplan = testplan, title = title,
                                       description = description,
                                       allocated_to = allocate_to,
                                       allocated_by = request.user,
                                       client_device = client_device,
                                       browsers = browser_name, category=category)
        execution_task.save()
        
        
        testcases = TestCase.objects.filter(category = category)
        
        for testcase in testcases:
            execution_history =  ExecutionHistory(execution = execution_task, testcase = testcase)
            execution_history.save()
        
        return HttpResponseRedirect("/execution/get/"+str(tp_id)+"/")
        
    else:
        return render_to_response('allocate_task.html', args, context_instance=RequestContext(request))
    
def get_task_detail(request, tp_id, et_id):
    testplan = TestPlan.objects.get(id = tp_id)
    execution_task = ExecutionTask.objects.get(id = et_id)
    #categories =  execution.executionhistory_set.values('testcase__category__name').distinct()
    
    return render_to_response('task_detail.html', {'testplan': testplan,'execution_task': execution_task, 'active':'active'}, context_instance=RequestContext(request))

def task_testcases(request, tp_id, et_id):
    testplan = TestPlan.objects.get(id = tp_id)
    execution_task = ExecutionTask.objects.get(id = et_id)
    execution_history = execution_task.executionhistory_set.all()
    
    return render_to_response('task_testcases.html', {'testplan': testplan,'execution_task': execution_task, 'execution_history':execution_history, 'active':'active'}, context_instance=RequestContext(request))
    
    
@csrf_exempt
def execute_tc(request,tp_id, et_id):
    
    #execution_history = ExecutionHistory.objects.get(id=eh_id)
    #print request.POST.get('json_data')
    json_obj = json.loads(request.POST.get('json_data'))
    
    for obj in json_obj:
        
        execution_history = ExecutionHistory.objects.get(id=obj['eh_id'])
        execution_history.result = obj['eh_result']
        
        if obj['eh_result'] == 'PASS':
            execution_history.bugid = 0
            execution_history.comment = ''
        elif obj['eh_result'] == 'FAIL':
            execution_history.bugid = obj['eh_bugid']
            execution_history.comment = obj['comment']
        elif obj['eh_result'] == 'NAp':
            execution_history.comment = obj['comment']
        else:
            execution_history.comment = obj['comment']
            
        execution_history.executed_by = request.user
        execution_history.save()
        
    # Calculate execution task status.
    execution_task = ExecutionTask.objects.get(id=et_id)
        
    total_tc = execution_task.executionhistory_set.count()
    passed_tc = execution_task.passed()
    failed_tc = execution_task.failed()
    nap_tc = execution_task.nap()
     
    execution_status = ( (passed_tc + failed_tc + nap_tc)/total_tc ) * 100
      
    execution_task.status = execution_status
        
    execution_task.save()
    
    # Calculate testplan status.
    testplan = TestPlan.objects.get(id=tp_id)
    
        
    return HttpResponse("done")

executionmgmt/templates/allocate_task.html
{% extends 'base.html' %}


{% block content %}


<div id="page-wrapper" class = "col-lg-12">

            <div class="container-fluid">
				
                <!-- Page Heading -->
                
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Allocate Task
                             
                        </h1>
                        
                    </div>
                    <ol class="breadcrumb">
						  <li><a href="/">Home</a></li>
						  <li><a href="/execution">Test Plan Home</a></li>
						  <li class="active">Allocate new task</li>
					</ol>
                </div>
                <!-- /.row -->

                <div class="row">
                    
                    
                <div>
            </div>
            <!-- /.container-fluid -->

        </div>
         
        <!-- /#page-wrapper -->

    </div>
<div class="panel panel-default">
 
  <div class="panel-heading">{{testplan.title}}</div>
  <div class="panel-body">
    <p>{{testplan.description}}</p>
  </div>

  
  <table class="table">
  	<tr>
  		<th>Project</th>
  		<th>Build</th>
  		<th>Started on</th>
  		
  	</tr>
  	<tr>
  		<td>{{testplan.project}}</td>
  		<td>{{testplan.build.version}}</td>
  		<td>{{testplan.start_date}}</td>
  		
  	</tr>
  </table>
</div>
<form class="form-horizontal" method="POST" action="/execution/get/{{testplan.id}}/allocate/">
{% csrf_token %}
<fieldset>

<!-- Form Name -->
<legend>Create new task allocation</legend>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="title">Title</label>  
  <div class="col-md-5">
  <input id="title" name="title" type="text" placeholder="Title text" class="form-control input-md" required="">
  <span class="help-block">Example: Beta lifecycle for 4.3 allocated to Aakash</span>  
  </div>
</div>
<!-- Textarea -->
<div class="form-group">
  <label class="col-md-4 control-label" for="description">Description</label>
  <div class="col-md-5">                     
    <textarea class="form-control" id="description" name="description" placeholder="Description of this task"></textarea>
  </div>
</div>
<!-- Select Basic -->
<div class="form-group">
  <label class="col-md-4 control-label" for="allocate_to">Allocate To</label>
  <div class="col-md-5">
    <select id="allocate_to" name="allocate_to" class="form-control">
      {% for user in users %}
      <option value="{{user.id}}">{{user.username}}</option>
      {% endfor %}
    </select>
  </div>
</div>



<!-- Select Basic -->
<div class="form-group">
  <label class="col-md-4 control-label" for="category">Category (Module)</label>
  <div class="col-md-5">
    <select id="category" name="category" class="form-control">
    {% for category in testplan.project.category_set.all %}
      <option value="{{category.id}}">{{category.name}}</option>
    {% endfor %}
    </select>
  </div>
</div>


<!-- Select Multiple -->
<div class="form-group">
  <label class="col-md-4 control-label" for="client_device">Select Device</label>
  <div class="col-md-5">
    <select id="client_device" name="client_device" class="form-control">
      {% for client_device in client_devices %}
      	<option value="{{client_device.id}}">{{client_device.client_device}} - {{client_device.operating_system}}</option>
      {% endfor %}
    </select>
  </div>
</div>

<!-- Select Multiple -->
<div class="form-group">
  <label class="col-md-4 control-label" for="browsers">Select Browsers</label>
  <div class="col-md-5">
    <select id="browsers" name="browsers" class="form-control" multiple="multiple">
     {% for browser in browsers %}
      <option value="{{browser.id}}">{{browser.browser}}</option>
     {% endfor %}
    </select>
  </div>
</div>


<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="submit_btn"></label>
  <div class="col-md-4">
    <button id="submit_btn" name="submit_btn" class="btn btn-primary">Allocate</button>
  </div>
</div>

</fieldset>
</form>

  
   
                    
{% endblock %}

executionmgmt/templates/execution.html
{% extends 'base.html' %}

{% block content %}
<div id="page-wrapper" class = "col-lg-12">

            <div class="container-fluid">
				
                <!-- Page Heading -->
                
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            {{execution_task.title}} <small>{{execution_task.category}}</small>
                            
                        </h1>
                        
                    </div>
                </div>
                <!-- /.row -->

                <div class="row">
           
                <div>
            </div>
            <!-- /.container-fluid -->

        </div>
         
        <!-- /#page-wrapper -->

    </div>
    
<table id="tc_table" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <tr>
  	<th>Title</th>
  	<th>Steps to perform</th>
  	<th>Expected Result</th>
  	
  </tr>
  
  <tr>
  	<td>{{execution_history.testcase.title}}</td>
  	<td>{{execution_history.testcase.steps}}</td>
  	<td>{{execution_history.testcase.expected_result}}</td>
  </tr>
</table>


  
<ul class="pager">
	{% if execution_history.previous != None %}
 		 <li class="previous"><a href="/execution/execute/{{execution.id}}/tc/{{execution_history.previous.id}}">&larr; Previous</a></li>
  	{% else %}
  		 <li class="previous disabled"><a href="#">&larr; Previous</a></li>
  	{% endif %}
  	{% if execution_history.next != None %}
 		 <li class="next"><a href="/execution/execute/{{execution.id}}/tc/{{execution_history.next.id}}"> Next &rarr;</a></li>
  	{% else %}
  		 <li class="next disabled"><a href="#"> Next &rarr;</a></li>
  	{% endif %}
 
</ul>

<script>


    $('#tc_table').dataTable();

</script>
   
                    
{% endblock %}

executionmgmt/templates/execution_base.html
{% block execution_sidebar %}
active
{% endblock %}

executionmgmt/templates/execution_filter.html
{% extends 'base.html' %}

{% block content %}

<div id="page-wrapper" class = "col-lg-12">

            <div class="container-fluid">
				
                <!-- Page Heading -->
                
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            {{execution.title}} <small>Showing testcases filtered by {{filter_by}}</small>
                        </h1>
                        
                    </div>
                  
                </div>
                <!-- /.row -->

                <div class="row">
                    
                    
                <div>
            </div>
            <!-- /.container-fluid -->

        </div>
         
        <!-- /#page-wrapper -->
<div class="row">


<label class="col-lg-2 control-label" for="project">Filter by:</label>

  <div class="col-lg-4">
    <select id="result" name="result" class="form-control">
    <option value="all">All</option>
      <option value="pass">PASS</option>
      <option value="fail">FAIL</option>
      <option value="nap">Not Applicable</option>
      <option value="executed">All Executed</option>
      <option value="ne">Not executed</option>
    </select>
  </div>
</div>

		
   		<div class="col-lg-12">
                        <h2>Testcase summary</h2>
                        <div class="table-responsive">
                            <table id="result_table" class="table table-hover table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Testcase Title</th>
                                        
                                        <th>Result</th>
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                {% for eh  in execution_history %}
                                	{% if eh.result == "PASS"%}
                                   	 <tr class="success">
                                    
                                    {% elif eh.result == "FAIL"%}
                                   	 <tr class="danger">
                                    
                                    {% elif eh.result == "NAp"%}
                                   	 <tr class="warning">
                                   	 
                                   	{% else%}
                                   		<tr> 
                                    {%endif%}
                                    
                                        <td><a href="/execution/execute/{{execution.id}}/tc/{{eh.id}}/">{{eh.testcase.title}}</a></td>
                                        <td>{{eh.result}}</td>
                                        
                                        
                                    </tr>
                               {% endfor %}    
                                </tbody>
                            </table>
                        </div>
                    </div>
 


<script>

$(document).ready(function() {

	//$("select#result").prop('selectedIndex', 2);
	
		$('#result_table').dataTable( {
        "pagingType": "full_numbers"
   		 });
		var filter_by = "{{filter_by}}";
		
		switch(filter_by){
			
			case "Passed":
				$("#result").val("pass");
				break;
			case "Failed":
				$("#result").val("fail");
				break;
			case "Not Applicable":
				$("#result").val("nap");
				break;
			case "Not Executed":
				$("#result").val("ne");
				break;
			case "Executed":
				$("#result").val("executed");
				break;
				
			default:
				$("#result").val("all")
		}
		
	    $('#result').change(function() {
	    	
	    	var by = $("#result option:selected").val();
	    	window.location.href = "/execution/get/"+"{{ execution.id }}"+"/filter/?by="+by;	
	        
	        
	    });

	    function returnSuccess(data, textStatus, jqXHR)
		{
	    	alert(data);
	    	
	    	
		}	

	
	
});
</script>
                  
{% endblock %}

executionmgmt/templates/executions_home.html
{% extends 'base.html' %}
{% include 'execution_base.html' %}

{% block content %}


<div id="page-wrapper" class = "col-lg-12">

            <div class="container-fluid">
				
                <!-- Page Heading -->
                
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Current Test Plans
                             
                        </h1>
                        
                    </div>
                    <ol class="breadcrumb">
						  <li><a href="/">Home</a></li>
						  <li class="active">Test Plans</li>
					</ol>
                </div>
                <!-- /.row -->

                <div class="row">
                    
                    
                <div>
            </div>
            <!-- /.container-fluid -->

        </div>
         
        <!-- /#page-wrapper -->

    </div>
    
   
   
   <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Current test plans: <b>{{ testplans.count }}</b></div>
  <div class="panel-body">
   
  

  <!-- List group -->
  <ul class="list-group">
  

{% for item in dict_obj %}
   <p><li class="list-group-item"><h3><a href="/execution/get/{{ item.testplan.id }}/">{{item.testplan.title}}</a><a class="btn btn-primary pull-right noprint" role="button" href="/execution/exporttohtml/?tp_id={{item.testplan.id}}">Report</a></p></h3>
   <h4>Started On: {{item.testplan.start_date}} </h4>

   <div class="progress">
  <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="{{ item.status }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ item.status }}%">
    {{ item.status }}%
  </div>
	</div>
    
    </li>

   </ul>
</div>	
</div>
{% if user.groups.all.0.name == "qa_lead" %}
<a class="btn btn-primary" href="/execution/start/" role="button">Create New Test Plan</a>
{%endif%}

{%endfor%}

                    
{% endblock %}