projectmgmt/urls.py
from django.conf.urls import patterns, include, url
import projectmgmt.views as proj_views



urlpatterns = patterns('',
   
    url(r'^$', proj_views.index),
    url(r'^get/(?P<p_id>\d+)/$', proj_views.get_project_detail),
    url(r'^add/$', proj_views.add_project),
    url(r'^(?P<p_id>\d+)/category/add/$', proj_views.add_category),
    
    url(r'^getProjectCategory.psp$', proj_views.get_project_category),
    url(r'^getBuildDetails.psp$', proj_views.get_build_details),
    url(r'^getBuilds.psp$', proj_views.get_builds),
    url(r'^(?P<p_id>\d+)/builds/add/$', proj_views.add_build),
    
   
)

tcms/urls.py
from django.conf.urls import patterns, include, url
from testcasemgmt import urls as testcase_urls

from django.contrib import admin
admin.autodiscover()
handler404 = 'tcms.views.pagenotfound'
handler403 = 'tcms.views.notauthorized'

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^testcase/', include(testcase_urls)),
    (r'^$', 'tcms.views.index'),
	(r'^home/', 'tcms.views.home'),
    (r'^login/$','tcms.views.login'),
    (r'^auth/$','tcms.views.auth_view'),
    (r'^logout/$','tcms.views.logout'),
    (r'^invalid/$','tcms.views.invalid_login'),

    url(r'^project/', include('projectmgmt.urls')),
    url(r'^execution/', include('executionmgmt.urls')),
)

projectmgmt/models.py
from django.db import models


# Project Models.

class Project(models.Model):
    name = models.CharField(max_length=200)
    description =  models.TextField()
    is_active = models.BooleanField(default = True)
    
    def __unicode__(self):
        return self.name
    

class Category(models.Model):
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=200)
    description =  models.TextField()
    is_active = models.BooleanField()
    
    def __unicode__(self):
        return self.name
    
class Build(models.Model):
    project = models.ForeignKey(Project)
    version = models.CharField(max_length=200)
    description =  models.TextField()
    
    def __unicode__(self):
        return self.version
    
    
       
    
class ClientDevice(models.Model):
    project = models.ForeignKey(Project)
    client_device = models.CharField(max_length=200)
    operating_system = models.CharField(max_length=200)
    
    def __unicode__(self):
        return self.client_device
    
class Browser(models.Model):
    browser = models.CharField(max_length=200)
    

projectmgmt/forms.py
from django import forms
from models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        
    

projectmgmt/views.py
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from models import Project,Category,Build
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse
from django.core.context_processors import csrf
from django.core.exceptions import PermissionDenied
from django.db.models import Max
from django.contrib.comments.feeds import LatestCommentFeed

import json

# Project views are here.

@login_required(login_url='/login')
def index(request):
    projects = Project.objects.filter(is_active=True)
    return render_to_response('project_home.html', {'projects' : projects, 'active':"active"})
   
@login_required(login_url='/login')
def get_project_detail(request,p_id=1):
    args = {}
    args.update(csrf(request))
    
    project = Project.objects.get(id=p_id)
    categories = project.category_set.all()
    latest_version = Build.objects.all().aggregate(Max('version'))
    latest_version = Build.objects.get(version = latest_version['version__max'])
    
    args['project'] = project
    args['categories'] = categories
    args['latest_version'] = latest_version
    
    
    return render_to_response('project_detail.html', args)

@login_required(login_url='/login')
def add_project(request):
    
    if request.user.groups.all()[0].name not in ["admin","qa_lead"]:
        raise PermissionDenied
    else:
        
        
        args = {}
        args.update(csrf(request))
        args['active'] = 'active'
        
        if request.POST:
            proj_name = request.POST['proj_name']
            proj_desc = request.POST['proj_desc']
            
            if Project.objects.filter(name = proj_name):
                args['message'] = 'Same project already exists.'
                return render_to_response('add_project.html', args)
            else:
                project = Project(name = proj_name, description = proj_desc)
                project.save()
                print project.id   
                return HttpResponseRedirect('/project/get/'+str(project.id)+'/')
            
        else:
            
            return render_to_response('add_project.html', args)

@login_required(login_url='/login')
def add_category(request, p_id):
    args = {}
    args.update(csrf(request))
    project = Project.objects.get(id=p_id)
    args['project'] = project
    args['active'] = 'active'
    
    if request.POST:
        category_name = request.POST['category']
        category_desc = request.POST['description']
        
        if project.category_set.filter(name=category_name):
            args['message'] = 'Same category already exists in this project'
            return render_to_response('add_category.html', args)
        else:
            category = Category(project = project, name = category_name, description = category_desc)
            category.save()   
            return HttpResponseRedirect('/project/get/'+str(p_id)+"/")
        
    else:
        
        return render_to_response('add_category.html', args)

def get_project_category(request):
    project_id = request.GET['proj_id']
    data = []
    if Project.objects.get(id=project_id):
        project = Project.objects.get(id=project_id)
        
        for category in project.category_set.all():
            data.append({ "id": category.id, "name": category.name })
                      
    return HttpResponse(json.dumps(data, indent=4), 
                    mimetype="application/json") 
        
        

def get_build_details(request):
    build_id = request.GET['build']
    build = Build.objects.get(id = build_id)
    
    data = {"id": build.id,"project" : build.project.name, "description": build.description}
    return HttpResponse(json.dumps(data, indent=4), mimetype="application/json") 

def get_builds(request):
    project_id = request.GET['project']
    data = []
    if Project.objects.get(id=project_id):
        project = Project.objects.get(id=project_id)
        
        for build in project.build_set.all():
            data.append({ "id": build.id, "version": build.version })
                      
    return HttpResponse(json.dumps(data, indent=4), 
                    mimetype="application/json") 
    

def add_build(request, p_id):
    project = Project.objects.get(id=p_id)
    if request.POST:
        version = request.POST['version']
        description = request.POST['description']
        
        new_build = Build(version=version, description=description, project = project)
        
        new_build.save()
        return HttpResponseRedirect('/project/get/'+str(project.id)+'/')
        
    else:
        
        raise PermissionDenied
    
    

projectmgmt/templates/add_category.html
{% extends 'base.html' %}

{% block content %}
<div id="page-wrapper" class = "col-lg-12">

            <div class="container-fluid">
				
                <!-- Page Heading -->
                
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Add New Category to Project: {{ project.name }}
                             
                        </h1>
                        
                    </div>
                </div>
                <!-- /.row -->

                <div class="row">
                    
                    
                <div>
            </div>
            <!-- /.container-fluid -->

        </div>
         
        <!-- /#page-wrapper -->

    </div>
    
<form class="form-horizontal" action="/project/{{ project.id }}/category/add/" method="post">
{% csrf_token %}
<fieldset>

<!-- Form Name -->


<!-- Text input-->
<div class="form-group">
{% if message %}
	<div class="alert alert-danger">
	         <strong>Oh snap!</strong> {{message}}
	</div>
{% endif %}
  <label class="col-md-4 control-label" for="textinput">Category Name</label>  
  <div class="col-md-6">
  <input id="category" name="category" type="text" placeholder="Enter category name" required="" class="form-control input-md">
  <span class="help-block">Example: WebUI</span>  
  </div>
</div>

<!-- Textarea -->
<div class="form-group">
  <label class="col-md-4 control-label" for="textarea">Description</label>
  <div class="col-md-4">                     
    <textarea class="form-control" id="description" name="description" required="" placeholder="Enter category description"></textarea>
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="singlebutton"></label>
  <div class="col-md-4">
    <button id="singlebutton" name="singlebutton" class="btn btn-primary" type="submit">Add</button>
  </div>
  
</div>

</fieldset>
</form>



   
   
   
                    
{% endblock %}

projectmgmt/templates/add_project.html
{% extends 'base.html' %}

{% block content %}
<div id="page-wrapper" class = "col-lg-12">

            <div class="container-fluid">
				
                <!-- Page Heading -->
                
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Add New Project
                             
                        </h1>
                        
                    </div>
                </div>
                <!-- /.row -->

                <div class="row">
                    
                    
                <div>
            </div>
            <!-- /.container-fluid -->

        </div>
         
        <!-- /#page-wrapper -->

    </div>
    
<form class="form-horizontal" action="/project/add/" method="post">
{% csrf_token %}
<fieldset>

<!-- Form Name -->


<!-- Text input-->
<div class="form-group">
{% if message %}
	<div class="alert alert-danger">
	         <strong>Oh snap!</strong> {{message}}
	</div>
{% endif %}
  <label class="col-md-4 control-label" for="textinput">Project Name</label>  
  <div class="col-md-6">
  <input id="proj_name" name="proj_name" type="text" placeholder="Enter project name" required="" class="form-control input-md">
  <span class="help-block">Example: Gemini 4.2</span>  
  </div>
</div>

<!-- Textarea -->
<div class="form-group">
  <label class="col-md-4 control-label" for="textarea">Description</label>
  <div class="col-md-4">                     
    <textarea class="form-control" id="proj_desc" name="proj_desc" required="" placeholder="Enter project description"></textarea>
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="singlebutton"></label>
  <div class="col-md-4">
    <button id="singlebutton" name="singlebutton" class="btn btn-primary" type="submit">Save</button>
  </div>
  
</div>

</fieldset>
</form>



   
   
   
                    
{% endblock %}

projectmgmt/templates/project_base.html
{% block project_sidebar %}
active
{% endblock %}

projectmgmt/templates/project_detail.html
{% extends 'base.html' %}

{% block content %}
<div id="page-wrapper" class = "col-lg-12">

            <div class="container-fluid">
				
                <!-- Page Heading -->
                
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            {{project.name}} 
                        </h1>
                        <ol class="breadcrumb">
						  <li><a href="/">Home</a></li>
						  <li><a href="/project">Projects</a></li>
						  <li class="active">Project Details</li>
						</ol>
                        
                    </div>
                </div>
                <!-- /.row -->

                <div class="row">
                    
                    
                <div>
            </div>
            <!-- /.container-fluid -->

        </div>
         
        <!-- /#page-wrapper -->

    </div>
    
 <!--   <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Project Name</h3>
  </div>
  <div class="panel-body">
    {{project.name}}
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Description</h3>
  </div>
  <div class="panel-body">
    {{project.description}}
  </div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">
    	<h3 class="panel-title">Categories</h3>
  	</div>
  	<div class="panel-body">
  		{% if categories.count > 0  %}
	    	<ul class="list-group">
	    		{% for category in categories %}
	    			<li class="list-group-item">{{ category.name }} -- {{category.description}} </li>
	    		{% endfor %}
	  		</ul>
		{% else %}
			<div class="panel-body">
    			No Categories found!!
  			</div>
  		{% endif %}
  	
  	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading">
    	<h3 class="panel-title">Builds</h3>
  	</div>
  	
	  	<div class="panel-body">
		  	<div class="row">
	  			<label class="col-lg-2 control-label" for="build">Select build</label>
	  				<div class="col-lg-3">
		  				{% if project.build_set.count > 0  %}
			    			<select id="build" name="result" class="form-control">
		   						{% for build in project.build_set.all %}
		   							<option value="{{build.id}}">{{build.version}}</option>
		      					{% endfor %}
		      				</select>
						{% else %}
							<div class="panel-body">
		    					No builds found!!
		  					</div>
		  				{% endif %}
		  		
		  			</div>
		  	</div>
		  	
		  	<div class="row">
	  			<label class="col-lg-2 control-label" for="description">Description</label>
				  	<div class="col-lg-4">
				  		<p id="description"></p>
				  	</div>
		  	</div>
	  	</div>
   
</div>   

<div class="panel panel-default">
	<div class="panel-heading">
    	<h3 class="panel-title">Environment used</h3>
  	</div>
  	<div class="panel-body">
  		{% if project.clientdevice_set.count > 0  %}
	    	<ul class="list-group">
	    		{% for client_device in project.clientdevice_set.all %}
	    			<li class="list-group-item">{{ client_device }} -- {{client_device.operating_system}} </li>
	    		{% endfor %}
	  		</ul>
		{% else %}
			<div class="panel-body">
    			No Environment details found!!
  			</div>
  		{% endif %}
  	
  	</div>
</div> -->
 <div class="box box-solid">
                                <div class="box-header">
                                    <i class="fa fa-fw fa-folder"></i>
                                    <h3 class="box-title">{{project.name}}</h3>
                                </div><!-- /.box-header -->
                                
                                <div class="box-body">
                                    <dl class="dl-horizontal">
                                        <dt><h3><b>Project ID:</b></h3></dt>
                                        <dd><h3>{{project.id}}</h3></dd>
                                        <dt><h3><b>Description:</b></h3></dt>
                                        <dd><h3>{{project.description|linebreaks}}</h3></dd>
                                        
                                        <dt><h3><b>Categories:</b></h3></dt>
                                        {% if categories.count > 0  %}
                                        	
                                        		{%for category in project.category_set.all %}
                                        			<dd><h3>{{category.name}}- <small>{{category.description}}</small></h3></dd>
                                        		{%endfor%}
                                       	{%else%}
                                       		<dd><h3 class="text-red">No categories available!!</h3></dd>
                                       	{%endif%}
                                        	
                                       <dt><h3><b>Latest build:</b></h3></dt>
                                       {% if project.build_set.all.count > 0  %}
                                       
					                  		<dd><h3 class="text-green">{{ latest_version.version }} - <small>{{ latest_version.description|linebreaks }}</small></h3></dd>
                                       {%else%}
                                       		<dd><h3 class="text-red">No builds found!!</h3></dd>
                                       {%endif%}
                                       
                                       <dd>
                                       <!-- Button trigger modal -->
										<button class="btn btn-primary" data-toggle="modal" data-target="buildsModal" id="showBuild">
										  More
										</button>
										
										<!-- Modal -->
										<div class="modal fade bs-example-modal-lg" id="buildsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
										  <div class="modal-dialog modal-lg">
										    <div class="modal-content">
										      <div class="modal-header">
										        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
										        <h4 class="modal-title" id="myModalLabel">All builds for {{project}}</h4>
										      </div>
										      <div class="modal-body">
										      <form class="form-horizontal" method="POST" action="/project/{{project.id}}/builds/add/">
										      {%csrf_token%}
<fieldset>

<!-- Form Name -->
<legend>Add New Build</legend>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="version">Build Version</label>  
  <div class="col-md-5">
  <input id="version" name="version" type="text" placeholder="Enter build version" class="form-control input-md" required="">
  <span class="help-block">Ex: 4.3.0.023</span>  
  </div>
</div>

<!-- Textarea -->
<div class="form-group">
  <label class="col-md-4 control-label" for="description">Description</label>
  <div class="col-md-4">                     
    <textarea class="form-control" id="description" name="description" placeholder="Description"></textarea>
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="add_build"></label>
  <div class="col-md-4">
    <button id="add_build" name="add_build" class="btn btn-primary">Add Build</button>
  </div>
</div>

</fieldset>
</form>
										      
										      	<div class="box-body no-padding">
                                    <table class="table">
                                        <tbody><tr>
                                            
                                            <th>Build Version</th>
                                            <th>Description</th>
                                            
                                        </tr>
                                        {% for build in project.build_set.all %}
                                        <tr>
                                            
                                            	<td>{{build.version}}</td>
                                            	<td>{{build.description|linebreaks}}</td>
                                            
                                        </tr>
                                        {% endfor %}
                                       
                                    </tbody></table>
                                </div>
                                
                                
										        
										      </div>
										      <div class="modal-footer">
										        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
										        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
										      </div>
										    </div>
										  </div>
										</div>
                                       </dd>
                                    </dl>
                                </div><!-- /.box-body -->
                            </div>
<script type="text/javascript">	

$('#showBuild').click(function(){
	$('#buildsModal').modal('show');	
});

		
/*
		$.ajax({
			type : "GET",
			url : "/project/getBuildDetails.psp",
			data : {
				"build" : $('#build').val()
			},
			success : returnSuccess,
			dataType : "json",
		});
	    $('#build').change(function() {
	    	
	    	$.ajax({
	    		type : "GET",
	    		url : "/project/getBuildDetails.psp",
	    		data : {
	    			"build" : $('#build').val()
	    		},
	    		success : returnSuccess,
	    		dataType : "json",
	    	});
	        
	        
	    });
	    
	    function returnSuccess(data, textStatus, jqXHR)
		{
	    	$('#description').html(data.description);
	    	
	    	
		}	

	*/
</script>
                    
{% endblock %}

projectmgmt/templates/project_home.html
{% extends 'base.html' %}
{% include 'project_base.html' %}

{% block content %}


<div id="page-wrapper" class = "col-lg-12">

            <div class="container-fluid">
				
                <!-- Page Heading -->
                
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Projects
                             <small>All projects</small>
                        </h1>
                        
                        
                    </div>
                    <ol class="breadcrumb">
						  <li><a href="/">Home</a></li>
						  <li class="active">Projects</li>
					</ol>
                </div>
                <!-- /.row -->

                <div class="row">
                    
                    
                <div>
            </div>
            <!-- /.container-fluid -->

        </div>
         
        <!-- /#page-wrapper -->

    </div>
    
   
   
   <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Current projects</div>
  <div class="panel-body">
    <p><b>Total projects: {{ projects.count }}</b></p>
  </div>

  <!-- List group -->
  <ul class="list-group">
  
  {% for project in projects %}
    <li class="list-group-item"><a href="/project/get/{{ project.id }}">{{project.name}}</a></li>
    
  {% endfor %} 
   </ul>
</div>
<!--  <a class="btn btn-primary" href="/project/add/" role="button">Add New</a>-->
                    
{% endblock %}